export const GET_IP_ADDRESS = "GET_IP_ADDRESS";
export const GET_IP_ADDRESS_SUCCESS = "GET_IP_ADDRESS_SUCCESS";
export const GET_IP_ADDRESS_ERROR = "GET_IP_ADDRESS_ERROR";

export const GET_LEAGUE_GAME = "GET_LEAGUE_GAME";
export const GET_LEAGUE_GAME_SUCCESS = "GET_LEAGUE_GAME_SUCCESS";
export const GET_LEAGUE_GAME_ERROR = "GET_LEAGUE_GAME_ERROR";

export const GET_GAME = "GET_GAME";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_ERROR = "GET_GAME_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGGOUT_USER = "LOGGOUT_USER";
export const LOGGOUT_USER_SUCCESS = "LOGGOUT_USER_SUCCESS";
export const LOGGOUT_USER_ERROR = "LOGGOUT_USER_ERROR";

export const BUY_CREDITS = "BUY_CREDITS";
export const BUY_CREDITS_SUCCESS = "BUY_CREDITS_SUCCESS";
export const BUY_CREDITS_ERROR = "BUY_CREDITS_ERROR";

export * from "./games/actions";
