export const GET_IP_ADDRESS = "GET_IP_ADDRESS";
export const GET_IP_ADDRESS_SUCCESS = "GET_IP_ADDRESS_SUCCESS";
export const GET_IP_ADDRESS_ERROR = "GET_IP_ADDRESS_ERROR";

export const GET_LEAGUE_GAME = "GET_LEAGUE_GAME";
export const GET_LEAGUE_GAME_SUCCESS = "GET_LEAGUE_GAME_SUCCESS";
export const GET_LEAGUE_GAME_ERROR = "GET_LEAGUE_GAME_ERROR";

export const GET_GAME = "GET_GAME";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_ERROR = "GET_GAME_ERROR";

export * from "./games/actions";
