export const GET_NEXT_GAMES = "GET_NEXT_GAMES";
export const GET_NEXT_GAMES_SUCCESS = "GET_NEXT_GAMES_SUCCESS";
export const GET_NEXT_GAMES_ERROR = "GET_NEXT_GAMES_ERROR";

//? User
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGGOUT_USER = "LOGGOUT_USER";
export const LOGGOUT_USER_SUCCESS = "LOGGOUT_USER_SUCCESS";
export const LOGGOUT_USER_ERROR = "LOGGOUT_USER_ERROR";

export const BUY_CREDITS = "BUY_CREDITS";
export const BUY_CREDITS_SUCCESS = "BUY_CREDITS_SUCCESS";
export const BUY_CREDITS_ERROR = "BUY_CREDITS_ERROR";

export const RESET_PASSWORD_LINK = "RESET_PASSWORD_LINK";
export const RESET_PASSWORD_LINK_SUCCESS = "RESET_PASSWORD_LINK_SUCCESS";
export const RESET_PASSWORD_LINK_ERROR = "RESET_PASSWORD_LINK_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export * from "./games/actions";
